version: '3.9'

services:
  luke_site_mvc:
    image: ${DOCKER_REGISTRY-}lukesitemvc
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SubredditDb
    ports:
      - 5432:5432
    restart: always

  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
    restart: always
