version: '3.9'

services:
  luke_site_mvc:
    image: ${DOCKER_REGISTRY-}lukesitemvc
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Pass@word123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
