version: '3.4'

services:
  luke_site_mvc:
    image: ${DOCKER_REGISTRY-}lukesitemvc
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - sqlserver

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"     

  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
